// Built-in quizzes shipped with CyberQuiz (cryptography + network security).
module.exports = [
  /* ── Cryptography: Fundamentals ── */
  {
    title: "Cryptography Fundamentals",
    description: "Core concepts every CS undergrad should know: symmetric ciphers, the CIA triad, block sizes and modes.",
    category: "Cryptography",
    timeLimit: 300,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "In the CIA triad, what does the 'C' stand for?", options: ["Cryptography", "Confidentiality", "Compliance", "Certification"], correct: 1 },
      { q: "Symmetric encryption uses...", options: ["A public/private key pair", "The same key for encryption and decryption", "No key at all", "A one-way hash function"], correct: 1 },
      { q: "Which of these is a symmetric block cipher?", options: ["RSA", "AES", "Diffie-Hellman", "ECC"], correct: 1 },
      { q: "The Caesar cipher is an example of a...", options: ["Transposition cipher", "Substitution cipher", "Public-key cipher", "Hash function"], correct: 1 },
      { q: "Kerckhoffs's principle says a system's security should rest on...", options: ["Secrecy of the algorithm", "Secrecy of the key only", "Length of the plaintext", "The encoding scheme"], correct: 1 },
      { q: "AES processes data in blocks of how many bits?", options: ["56", "64", "128", "512"], correct: 2 },
      { q: "A stream cipher typically encrypts...", options: ["One fixed block at a time", "One bit or byte at a time", "Only 64-bit blocks", "Using a public key"], correct: 1 },
      { q: "Which mode produces identical ciphertext for identical plaintext blocks (unsafe for images)?", options: ["CBC", "CTR", "ECB", "GCM"], correct: 2 },
      { q: "The main practical weakness of symmetric cryptography is...", options: ["It is always too slow", "Secure key distribution between parties", "It cannot encrypt large files", "It provides no confidentiality"], correct: 1 },
      { q: "DES was retired as a standard mainly because...", options: ["It was too slow", "Its 56-bit key was vulnerable to brute force", "It could not decrypt data", "It used asymmetric keys"], correct: 1 },
    ],
  },

  /* ── Cryptography: Asymmetric & PKI ── */
  {
    title: "Asymmetric Encryption & PKI",
    description: "Public-key cryptography, RSA, Diffie-Hellman, digital certificates and certificate authorities.",
    category: "Cryptography",
    timeLimit: 300,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "A message encrypted with a recipient's public key can be decrypted with...", options: ["The sender's public key", "The recipient's private key", "A shared symmetric key", "Any public key"], correct: 1 },
      { q: "RSA's security relies on the difficulty of...", options: ["Computing elliptic-curve discrete logs", "Factoring the product of two large primes", "Reversing a hash", "Solving linear equations"], correct: 1 },
      { q: "Diffie-Hellman is primarily used for...", options: ["Encrypting large files directly", "Secure key exchange over an insecure channel", "Hashing passwords", "Compressing data"], correct: 1 },
      { q: "A digital certificate binds a public key to...", options: ["A private key", "An identity (an entity)", "A symmetric session key", "An IP address"], correct: 1 },
      { q: "In a PKI, who issues and signs digital certificates?", options: ["A Certificate Authority (CA)", "The DNS server", "The end user", "An ISP"], correct: 0 },
      { q: "To create a digital signature, the sender encrypts the message hash with their...", options: ["Public key", "Private key", "Recipient's public key", "Shared secret"], correct: 1 },
      { q: "Compared with symmetric encryption, asymmetric encryption is generally...", options: ["Much faster", "Slower / more computationally expensive", "Identical in speed", "Unable to provide confidentiality"], correct: 1 },
      { q: "Which scheme uses elliptic curves to give equivalent security with smaller keys?", options: ["RSA", "AES", "ECC", "DES"], correct: 2 },
      { q: "Revoked certificates are typically published in a...", options: ["ARP table", "Certificate Revocation List (CRL)", "DNS zone file", "Routing table"], correct: 1 },
    ],
  },

  /* ── Cryptography: Hashing & Signatures ── */
  {
    title: "Hashing, Integrity & Digital Signatures",
    description: "Hash properties, MACs, salting, and what digital signatures do (and don't) provide.",
    category: "Cryptography",
    timeLimit: 240,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "A cryptographic hash function produces output that is...", options: ["Variable-length", "Fixed-length", "Always 8 bytes", "Easily reversible"], correct: 1 },
      { q: "Which property makes it infeasible to find two inputs with the same hash?", options: ["Pre-image resistance", "Collision resistance", "Confidentiality", "Availability"], correct: 1 },
      { q: "Which hash algorithm is considered broken due to practical collisions?", options: ["SHA-256", "MD5", "SHA-3", "BLAKE2"], correct: 1 },
      { q: "Hash functions, on their own, primarily provide...", options: ["Confidentiality", "Integrity", "Availability", "Key exchange"], correct: 1 },
      { q: "An HMAC combines a hash function with...", options: ["A second hash", "A secret key", "A public key", "A timestamp only"], correct: 1 },
      { q: "Adding a unique salt to a password hash mainly defends against...", options: ["Brute force on one hash", "Precomputed rainbow-table attacks", "SQL injection", "Phishing"], correct: 1 },
      { q: "Digital signatures provide all of the following EXCEPT...", options: ["Authentication", "Integrity", "Non-repudiation", "Confidentiality"], correct: 3 },
      { q: "The avalanche effect means...", options: ["The hash grows with input size", "A tiny input change drastically alters the output", "Collisions are common", "The output is reversible"], correct: 1 },
    ],
  },

  /* ── Network Security: Basics ── */
  {
    title: "Network Security Basics",
    description: "Foundational networking and security concepts: the OSI model, common protocols, firewalls, and everyday threats.",
    category: "Network Security",
    timeLimit: 480,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "How many layers does the OSI model have?", options: ["4", "5", "7", "9"], correct: 2 },
      { q: "Which OSI layer is responsible for end-to-end communication and uses TCP/UDP?", options: ["Network layer", "Transport layer", "Session layer", "Data Link layer"], correct: 1 },
      { q: "What does DNS stand for?", options: ["Data Network Service", "Domain Name System", "Dynamic Network Security", "Distributed Naming Scheme"], correct: 1 },
      { q: "Which protocol automatically assigns IP addresses to devices on a network?", options: ["FTP", "SMTP", "DHCP", "SNMP"], correct: 2 },
      { q: "What is the default port for HTTPS?", options: ["80", "21", "443", "8080"], correct: 2 },
      { q: "A firewall primarily operates by...", options: ["Encrypting all traffic", "Filtering network traffic based on rules", "Assigning IP addresses", "Compressing packets"], correct: 1 },
      { q: "Which type of address uniquely identifies a network interface at the Data Link layer?", options: ["IP address", "MAC address", "Port number", "Subnet mask"], correct: 1 },
      { q: "What does NAT stand for in networking?", options: ["Network Access Token", "Network Address Translation", "Node Authentication Table", "Null Acknowledgement Transfer"], correct: 1 },
      { q: "Which protocol is connection-oriented and guarantees delivery?", options: ["UDP", "ICMP", "TCP", "ARP"], correct: 2 },
      { q: "A phishing attack attempts to...", options: ["Flood a server with traffic", "Trick users into revealing sensitive information", "Exploit a buffer overflow", "Intercept encrypted packets"], correct: 1 },
      { q: "What does VPN stand for?", options: ["Virtual Private Network", "Verified Packet Node", "Variable Port Number", "Volatile Public Network"], correct: 0 },
      { q: "Which device connects multiple networks and forwards packets based on IP addresses?", options: ["Hub", "Switch", "Router", "Repeater"], correct: 2 },
      { q: "A Denial of Service (DoS) attack aims to...", options: ["Steal user credentials", "Make a service unavailable to legitimate users", "Decrypt encrypted traffic", "Gain root access to a server"], correct: 1 },
      { q: "HTTPS provides security over HTTP by using...", options: ["Base64 encoding", "TLS/SSL encryption", "IPsec tunneling", "VLAN tagging"], correct: 1 },
      { q: "Which of the following is a private IP address range (RFC 1918)?", options: ["8.8.8.0/24", "172.16.0.0/12", "1.1.1.0/24", "200.0.0.0/8"], correct: 1 },
    ],
  },

  /* ── Network Security: Intermediate ── */
  {
    title: "Network Security Intermediate",
    description: "Subnetting, TCP/IP internals, IDS/IPS, VPNs, wireless security, and common network attacks.",
    category: "Network Security",
    timeLimit: 600,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "How many usable host addresses does a /28 subnet provide?", options: ["14", "16", "30", "62"], correct: 0 },
      { q: "In the TCP three-way handshake, what is the correct sequence of flags?", options: ["SYN -> ACK -> SYN-ACK", "SYN -> SYN-ACK -> ACK", "ACK -> SYN -> FIN", "SYN -> FIN -> ACK"], correct: 1 },
      { q: "ARP poisoning attacks work by...", options: ["Flooding the network with ICMP packets", "Sending fake ARP replies to associate the attacker's MAC with a legitimate IP", "Injecting malicious DNS responses", "Exploiting weak WPA2 passwords"], correct: 1 },
      { q: "What is the key difference between an IDS and an IPS?", options: ["IDS encrypts traffic; IPS does not", "IDS only detects and alerts; IPS can actively block threats", "IPS operates at Layer 2; IDS at Layer 7", "They are identical in function"], correct: 1 },
      { q: "A DMZ (demilitarised zone) in network architecture is used to...", options: ["Block all external traffic", "Host public-facing services isolated from the internal network", "Encrypt internal communications", "Assign dynamic IP addresses"], correct: 1 },
      { q: "Which VPN protocol encapsulates packets at the IP layer and provides both authentication and encryption?", options: ["PPTP", "L2TP alone", "IPsec", "SOCKS5"], correct: 2 },
      { q: "What is the primary security benefit of a VLAN?", options: ["It encrypts all frames", "It logically segments traffic to limit broadcast domains and contain breaches", "It authenticates all devices", "It doubles available bandwidth"], correct: 1 },
      { q: "WPA2 uses which encryption algorithm in its default CCMP mode?", options: ["DES", "3DES", "AES", "RC4"], correct: 2 },
      { q: "A man-in-the-middle (MITM) attack works by...", options: ["Crashing the target server", "Positioning the attacker between two communicating parties to eavesdrop or alter data", "Sending millions of login attempts", "Exploiting a SQL injection flaw"], correct: 1 },
      { q: "Which tool is most commonly used for network port scanning?", options: ["Wireshark", "Nmap", "Metasploit", "Snort"], correct: 1 },
      { q: "DNS cache poisoning inserts malicious records into a DNS resolver's cache in order to...", options: ["Slow down DNS lookups", "Redirect users to fraudulent websites", "Prevent DNSSEC validation", "Block UDP traffic"], correct: 1 },
      { q: "A stateful firewall tracks network connections by...", options: ["Inspecting only the source IP header", "Maintaining a state table of active connections and validating packets against it", "Blocking all UDP traffic by default", "Using deep packet inspection on every byte"], correct: 1 },
      { q: "802.1X is a standard for...", options: ["Wireless encryption algorithms", "Port-based network access control (authentication before network access)", "Virtual LAN tagging", "Spanning Tree Protocol"], correct: 1 },
      { q: "In a SYN flood attack, the attacker...", options: ["Sends oversized UDP packets", "Sends many SYN packets without completing the handshake, exhausting server resources", "Forges DNS responses", "Replays captured authentication tokens"], correct: 1 },
      { q: "Which protocol is used to securely manage network devices and is preferred over Telnet?", options: ["FTP", "SNMPv1", "SSH", "HTTP"], correct: 2 },
    ],
  },

  /* ── Network Security: Advanced ── */
  {
    title: "Network Security Advanced",
    description: "Advanced topics: BGP security, zero-trust, TLS internals, APTs, DPI, DNSSEC, and protocol-level exploits.",
    category: "Network Security",
    timeLimit: 720,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "BGP hijacking is dangerous because...", options: ["It crashes routers by sending malformed packets", "An autonomous system falsely advertises IP prefixes, rerouting internet traffic through the attacker", "It disables DNSSEC validation globally", "It exploits a flaw in TLS 1.3 handshakes"], correct: 1 },
      { q: "In IPsec, what is the difference between Tunnel mode and Transport mode?", options: ["Tunnel mode encrypts only the payload; Transport mode encrypts the entire packet", "Tunnel mode wraps the entire original IP packet inside a new IP packet; Transport mode only encrypts the payload", "They are functionally identical", "Transport mode requires IKEv2; Tunnel mode uses IKEv1 only"], correct: 1 },
      { q: "TLS 1.3 improves on TLS 1.2 primarily by...", options: ["Adding support for MD5 hashes", "Removing weak cipher suites and reducing the handshake to 1-RTT", "Requiring a longer RSA key size", "Mandating the use of ECC exclusively"], correct: 1 },
      { q: "DNSSEC protects against DNS spoofing by...", options: ["Encrypting DNS query payloads end-to-end", "Digitally signing DNS resource records so resolvers can verify authenticity", "Requiring HTTPS for all DNS traffic", "Blocking UDP port 53 and forcing TCP"], correct: 1 },
      { q: "A Zero Trust architecture is built on the principle of...", options: ["Trusting all internal network traffic by default", "Never trusting any entity implicitly - always verify identity and enforce least-privilege regardless of network location", "Using a single strong perimeter firewall", "Encrypting only data at rest"], correct: 1 },
      { q: "An Advanced Persistent Threat (APT) is characterised by...", options: ["A quick smash-and-grab attack lasting minutes", "A prolonged stealthy campaign by a well-resourced attacker targeting a specific organisation over months or years", "Automated malware with no human operator", "A volumetric DDoS attack"], correct: 1 },
      { q: "Deep Packet Inspection (DPI) differs from traditional packet filtering because...", options: ["DPI only inspects IP headers", "DPI examines the full payload content of packets enabling detection of threats hidden inside application data", "DPI works exclusively at Layer 2", "DPI cannot handle encrypted traffic"], correct: 1 },
      { q: "Certificate pinning is a defence technique that...", options: ["Forces certificates to use 4096-bit RSA keys", "Hard-codes expected certificates or public keys in the client preventing acceptance of fraudulent CA-signed certificates", "Prevents certificate revocation", "Encrypts the TLS certificate during transmission"], correct: 1 },
      { q: "Which of the following best describes a side-channel attack?", options: ["Exploiting a vulnerability in application source code", "Gaining information from physical implementation characteristics (power, timing, EM emissions) rather than algorithm weaknesses", "A MITM attack on an encrypted channel", "SQL injection via a web form"], correct: 1 },
      { q: "In Kerberos authentication, the Ticket-Granting Ticket (TGT) is issued by...", options: ["The resource server", "The client browser", "The Key Distribution Center (KDC) Authentication Service", "An LDAP directory server"], correct: 2 },
      { q: "A Pass-the-Hash attack abuses...", options: ["Weak SSL certificates", "The fact that NTLM authentication accepts a password hash directly without requiring the plaintext password", "A BGP route leak", "Forged Kerberos tickets with no expiry"], correct: 1 },
      { q: "Network micro-segmentation reduces lateral movement risk by...", options: ["Placing all servers in a single VLAN with strict ACLs", "Dividing the network into small zones with strict east-west traffic controls between each workload", "Disabling routing between subnets entirely", "Using a host-based IPS on every server"], correct: 1 },
      { q: "Which attack exploits the trust relationship between a client and server by injecting packets into an established TCP session?", options: ["IP spoofing", "TCP session hijacking", "DNS poisoning", "SSL stripping"], correct: 1 },
      { q: "Centralising control in an SDN controller introduces a security risk because...", options: ["It removes the need for firewalls", "It creates a high-value single point of failure and attack target", "It forces all traffic to use UDP", "It eliminates VLANs"], correct: 1 },
      { q: "An SSL stripping attack downgrades a connection by...", options: ["Stealing the server's private key", "Intercepting an HTTP redirect to HTTPS and serving the victim plain HTTP while maintaining HTTPS with the server", "Brute-forcing the TLS pre-master secret", "Injecting a malicious root CA certificate"], correct: 1 },
    ],
  },
];
