// Built-in, undergraduate-level cryptography quizzes shipped with CyberQuiz.
module.exports = [
  {
    title: "Cryptography Fundamentals",
    description: "Core concepts every CS undergrad should know: symmetric ciphers, the CIA triad, block sizes and modes.",
    category: "Cryptography",
    timeLimit: 300,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "In the CIA triad, what does the “C” stand for?", options: ["Cryptography", "Confidentiality", "Compliance", "Certification"], correct: 1 },
      { q: "Symmetric encryption uses…", options: ["A public/private key pair", "The same key for encryption and decryption", "No key at all", "A one-way hash function"], correct: 1 },
      { q: "Which of these is a symmetric block cipher?", options: ["RSA", "AES", "Diffie–Hellman", "ECC"], correct: 1 },
      { q: "The Caesar cipher is an example of a…", options: ["Transposition cipher", "Substitution cipher", "Public-key cipher", "Hash function"], correct: 1 },
      { q: "Kerckhoffs’s principle says a system’s security should rest on…", options: ["Secrecy of the algorithm", "Secrecy of the key only", "Length of the plaintext", "The encoding scheme"], correct: 1 },
      { q: "AES processes data in blocks of how many bits?", options: ["56", "64", "128", "512"], correct: 2 },
      { q: "A stream cipher typically encrypts…", options: ["One fixed block at a time", "One bit or byte at a time", "Only 64-bit blocks", "Using a public key"], correct: 1 },
      { q: "Which mode produces identical ciphertext for identical plaintext blocks (unsafe for images)?", options: ["CBC", "CTR", "ECB", "GCM"], correct: 2 },
      { q: "The main practical weakness of symmetric cryptography is…", options: ["It is always too slow", "Secure key distribution between parties", "It cannot encrypt large files", "It provides no confidentiality"], correct: 1 },
      { q: "DES was retired as a standard mainly because…", options: ["It was too slow", "Its 56-bit key was vulnerable to brute force", "It could not decrypt data", "It used asymmetric keys"], correct: 1 },
    ],
  },
  {
    title: "Asymmetric Encryption & PKI",
    description: "Public-key cryptography, RSA, Diffie–Hellman, digital certificates and certificate authorities.",
    category: "Cryptography",
    timeLimit: 300,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "A message encrypted with a recipient’s public key can be decrypted with…", options: ["The sender’s public key", "The recipient’s private key", "A shared symmetric key", "Any public key"], correct: 1 },
      { q: "RSA’s security relies on the difficulty of…", options: ["Computing elliptic-curve discrete logs", "Factoring the product of two large primes", "Reversing a hash", "Solving linear equations"], correct: 1 },
      { q: "Diffie–Hellman is primarily used for…", options: ["Encrypting large files directly", "Secure key exchange over an insecure channel", "Hashing passwords", "Compressing data"], correct: 1 },
      { q: "A digital certificate binds a public key to…", options: ["A private key", "An identity (an entity)", "A symmetric session key", "An IP address"], correct: 1 },
      { q: "In a PKI, who issues and signs digital certificates?", options: ["A Certificate Authority (CA)", "The DNS server", "The end user", "An ISP"], correct: 0 },
      { q: "To create a digital signature, the sender encrypts the message hash with their…", options: ["Public key", "Private key", "Recipient’s public key", "Shared secret"], correct: 1 },
      { q: "Compared with symmetric encryption, asymmetric encryption is generally…", options: ["Much faster", "Slower / more computationally expensive", "Identical in speed", "Unable to provide confidentiality"], correct: 1 },
      { q: "Which scheme uses elliptic curves to give equivalent security with smaller keys?", options: ["RSA", "AES", "ECC", "DES"], correct: 2 },
      { q: "Revoked certificates are typically published in a…", options: ["ARP table", "Certificate Revocation List (CRL)", "DNS zone file", "Routing table"], correct: 1 },
    ],
  },
  {
    title: "Hashing, Integrity & Digital Signatures",
    description: "Hash properties, MACs, salting, and what digital signatures do (and don’t) provide.",
    category: "Cryptography",
    timeLimit: 240,
    creatorName: "CyberQuiz Team",
    questions: [
      { q: "A cryptographic hash function produces output that is…", options: ["Variable-length", "Fixed-length", "Always 8 bytes", "Easily reversible"], correct: 1 },
      { q: "Which property makes it infeasible to find two inputs with the same hash?", options: ["Pre-image resistance", "Collision resistance", "Confidentiality", "Availability"], correct: 1 },
      { q: "Which hash algorithm is considered broken due to practical collisions?", options: ["SHA-256", "MD5", "SHA-3", "BLAKE2"], correct: 1 },
      { q: "Hash functions, on their own, primarily provide…", options: ["Confidentiality", "Integrity", "Availability", "Key exchange"], correct: 1 },
      { q: "An HMAC combines a hash function with…", options: ["A second hash", "A secret key", "A public key", "A timestamp only"], correct: 1 },
      { q: "Adding a unique “salt” to a password hash mainly defends against…", options: ["Brute force on one hash", "Precomputed rainbow-table attacks", "SQL injection", "Phishing"], correct: 1 },
      { q: "Digital signatures provide all of the following EXCEPT…", options: ["Authentication", "Integrity", "Non-repudiation", "Confidentiality"], correct: 3 },
      { q: "The “avalanche effect” means…", options: ["The hash grows with input size", "A tiny input change drastically alters the output", "Collisions are common", "The output is reversible"], correct: 1 },
    ],
  },
];
